version: '3'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "192.168.99.100:2181/kafka-single"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null