version: '2'
services:
    redis:
        image: redis:4.0
        ports: 
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - ./data:/data
            - ./log:/tmp/redis
        restart: always
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes