version: '2'
services:
    redis-master:
        image: redis:4.0
        ports: 
            - "6380:6379"
        volumes:
            - ./redis-master.conf:/usr/local/etc/redis/redis.conf
            #- ./data-master:/data
            - ./log-master:/tmp/redis
        #restart: always
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
    redis-slave1:
        image: redis:4.0
        ports: 
            - "6381:6379"
        volumes:
            - ./redis-slave.conf:/usr/local/etc/redis/redis.conf
            #- ./data-slave:/data
            - ./log-slave:/tmp/redis
        #restart: always
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        links: 
            - redis-master