version: '2'
services:
    redis1:
        image: redis:4.0
        volumes:
            - ./redis-36379.conf:/usr/local/etc/redis/redis.conf
            - ./log-redis1:/tmp/redis
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        network_mode: host
    redis2:
        image: redis:4.0
        volumes:
            - ./redis-36380.conf:/usr/local/etc/redis/redis.conf
            - ./log-redis2:/tmp/redis
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        network_mode: host
    redis3:
        image: redis:4.0
        volumes:
            - ./redis-36381.conf:/usr/local/etc/redis/redis.conf
            - ./log-redis3:/tmp/redis
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        network_mode: host
    redis1-slave:
        image: redis:4.0
        volumes:
            - ./redis-36382.conf:/usr/local/etc/redis/redis.conf
            - ./log-redis1-slave:/tmp/redis
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        network_mode: host
    redis2-slave:
        image: redis:4.0
        volumes:
            - ./redis-36383.conf:/usr/local/etc/redis/redis.conf
            - ./log-redis2-slave:/tmp/redis
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        network_mode: host
    redis3-slave:
        image: redis:4.0
        volumes:
            - ./redis-36384.conf:/usr/local/etc/redis/redis.conf
            - ./log-redis3-slave:/tmp/redis
        command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
        network_mode: host