version: '2'
services:
  #zookeeper:
    #image: wurstmeister/zookeeper
    #ports:
      #- "2181:2181"
  kafka1:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181/kafka-cluster
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PORT: 9092
  kafka2:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181/kafka-cluster
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PORT: 9093
  kafka3:
    image: wurstmeister/kafka:2.11-2.0.0
    ports:
      - "9094:9094"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181/kafka-cluster
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PORT: 9094
